version: '3.9'

services:

  postgres:
    image: postgres:15
    env_file:
      - .env
    environment:
      - PGPORT=${PG_PORT}
      - PGTZ=${TZ}
    ports:
      - ${PG_PORT}:${PG_PORT}
    networks:
      - order_api_net

  queue:
    image: rabbitmq:3-management
    env_file:
      - .env
    environment:
      - RABBITMQ_HOST=queue
    ports:
      - ${RABBITMQ_PORT}:${RABBITMQ_PORT}
      - ${RABBITMQ_HTTP_PORT}:${RABBITMQ_HTTP_PORT}
    networks:
      - order_api_net


  redis:
    image: redislabs/redismod
    expose:
      - ${REDIS_PORT}
    networks:
      - order_api_net

  celeryworker:
    build: .
    depends_on:
      - postgres
      - queue
      - redis
    env_file:
      - .env
    environment:
      - PG_HOST=postgres
      - REDIS_HOST=redis
      - RABBITMQ_HOST=queue
      - SERVER_NAME=${DOMAIN}
      - SERVER_HOST=https://${DOMAIN}
    networks:
      - order_api_net

  employee_service:
    build: .
    command: ./start.sh
    env_file:
      - .env
    environment:
      - APP_ENV=mongodb_cluster_prod
      - DEBUG=False
      - PG_HOST=postgres
      - RABBITMQ_HOST=queue
      - REDIS_HOST=redis
    depends_on:
      - postgres
    ports:
      - ${PORT}:${PORT}
    networks:
      - order_api_net

networks:
  order_api_net:
    name: custom_network
