apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-nginx-depl
  namespace: fastapi-ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-nginx
  template:
    metadata:
      labels:
        app: store-nginx
    spec:
      containers:
        - image: nginx:latest
          name: nginx-container
          ports:
            - containerPort: 80
          volumeMounts:
            - name: store-nginx-configmap
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: store-nginx-configmap
          configMap:
            name: store-nginx-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: store-nginx-svc
  namespace: fastapi-ecommerce
spec:
  type: NodePort
  selector:
    app: store-nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002

