apiVersion: v1
kind: ConfigMap
metadata:
  name: store-nginx-configmap
  namespace: fastapi-ecommerce
data:
  default.conf: |
    upstream store_svc {
        server store-svc:8082;
    }    
    
    server {

        listen 80;

        location / {
            proxy_pass http://store_svc;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host;
            proxy_redirect off;
        }
    }