apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-ecommerce-nginx
  namespace: fastapi-ecommerce
  labels:
    app: fastapi-ecommerce-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-ecommerce-nginx
  template:
    metadata:
      labels:
        app: fastapi-ecommerce-nginx
    spec:
      containers:
        - image: nginx:latest
          name: nginx
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              port: 80
              path: /api/v1/docs
            initialDelaySeconds: 15
          livenessProbe:
            httpGet:
              port: 80
              path: /api/v1/docs
            initialDelaySeconds: 15
            periodSeconds: 15
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
