version: '3.9'

services:

  proxy_service:
    image: nginx:latest
    container_name: proxy_service
    volumes:
      - ./config/includes:/etc/nginx/includes/
      - ./config:/etc/nginx/
      - ./certs:/etc/ssl/certs/nginx/
      - ../.volumes/proxy_service/logs:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
