version: '3.9'

services:

  store_service_router01:
    image: mongo:latest
    container_name: store_service_router01
    command: mongos --port 27017 --configdb rs-config-server/store_service_configsvr01:27017 --bind_ip_all
    ports:
      - "27017:27017"
    volumes:
      - ./scripts:/scripts
      - ../../.volumes/store_service_mongodb/router01_db:/data/db
      - ../../.volumes/store_service_mongodb/router01_config:/data/configdb
    restart: always

  store_service_configsvr01:
    image: mongo:latest
    container_name: store_service_configsvr01
    command: mongod --port 27017 --configsvr --replSet rs-config-server
    volumes:
      - ./scripts:/scripts
      - ../../.volumes/store_service_mongodb/configsvr01_db:/data/db
      - ../../.volumes/store_service_mongodb/configsvr01_config:/data/configdb
    ports:
      - "27119:27017"
    restart: always

  store_service_shard01_a:
    image: mongo:latest
    container_name: store_service_shard01_a
    command: mongod --port 27017 --shardsvr --replSet rs-shard-01
    volumes:
      - ./scripts:/scripts
      - ../../.volumes/store_service_mongodb/shard01_a_db:/data/db
      - ../../.volumes/store_service_mongodb/shard01_a_config:/data/configdb
    ports:
      - "27122:27017"
    restart: always
  store_service_shard01_b:
    image: mongo:latest
    container_name: store_service_shard01_b
    command: mongod --port 27017 --shardsvr --replSet rs-shard-01
    volumes:
      - ./scripts:/scripts
      - ../../.volumes/store_service_mongodb/shard01_b_db:/data/db
      - ../../.volumes/store_service_mongodb/shard01_b_config:/data/configdb
    ports:
      - "27123:27017"
    restart: always
  store_service_shard01_c:
    image: mongo:latest
    container_name: store_service_shard01_c
    command: mongod --port 27017 --shardsvr --replSet rs-shard-01
    volumes:
      - ./scripts:/scripts
      - ../../.volumes/store_service_mongodb/shard01_c_db:/data/db
      - ../../.volumes/store_service_mongodb/shard01_c_config:/data/configdb
    ports:
      - "27124:27017"
    restart: always


  store_service_shard02_a:
    image: mongo:latest
    container_name: store_service_shard02_a
    command: mongod --port 27017 --shardsvr --replSet rs-shard-02
    volumes:
      - ./scripts:/scripts
      - ../../.volumes/store_service_mongodb/shard02_a_db:/data/db
      - ../../.volumes/store_service_mongodb/shard02_a_config:/data/configdb
    ports:
      - "27125:27017"
    restart: always
  store_service_shard02_b:
    image: mongo:latest
    container_name: store_service_shard02_b
    command: mongod --port 27017 --shardsvr --replSet rs-shard-02
    volumes:
      - ./scripts:/scripts
      - ../../.volumes/store_service_mongodb/shard02_b_db:/data/db
      - ../../.volumes/store_service_mongodb/shard02_b_config:/data/configdb
    ports:
      - "27126:27017"
    restart: always
  store_service_shard02_c:
    image: mongo:latest
    container_name: store_service_shard02_c
    command: mongod --port 27017 --shardsvr --replSet rs-shard-02
    volumes:
      - ./scripts:/scripts
      - ../../.volumes/store_service_mongodb/shard02_c_db:/data/db
      - ../../.volumes/store_service_mongodb/shard02_c_config:/data/configdb
    ports:
      - "27127:27017"
    restart: always
