apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: fastapi-ecommerce
data:
  default.conf: |
    upstream ecommerce_project {
        server auth-service:80;
    }
    server {

        listen 80;

        location / {
            proxy_pass http://auth-service;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host;
            proxy_redirect off;
        }
    }