version: '3.9'

services:

  postgres:
    image: postgres:15
    env_file:
      - .env
    environment:
      - PGPORT=${PG_PORT}
      - PGTZ=${TZ}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - ${PG_PORT}:${PG_PORT}

  mongo:
    image: candis/mongo-replica-set
    ports:
      - "27017:27017"
      - "27018:27018"
      - "27019:27019"

  queue:
    image: rabbitmq:3-management
    env_file:
      - .env
    environment:
      - RABBITMQ_HOST=queue
    ports:
      - ${RABBITMQ_PORT}:${RABBITMQ_PORT}
      - ${RABBITMQ_HTTP_PORT}:${RABBITMQ_HTTP_PORT}

  redis:
    image: redislabs/redismod
    expose:
      - ${REDIS_PORT}


  celeryworker:
    build:
      context: order_service
      dockerfile: celeryworker.dockerfile
    depends_on:
      - postgres
      - queue
      - redis
    env_file:
      - .env
    environment:
      - PG_HOST=postgres
      - REDIS_HOST=redis
      - RABBITMQ_HOST=queue
      - SERVER_NAME=${DOMAIN}
      - SERVER_HOST=https://${DOMAIN}

  backend:
    build:
      context: order_service
      dockerfile: order_service/Dockerfile
    command: ./start.sh
    env_file:
      - .env
    environment:
      - PG_HOST=postgres
      - RABBITMQ_HOST=queue
      - REDIS_HOST=redis
    depends_on:
      - postgres
    ports:
      - ${PORT}:${PORT}


volumes:
  postgres-data:
