version: '3.9'

services:

  proxy:
    build: .
    env_file:
      - ../../.env
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/ssl/certs/nginx/
    ports:
      - "80:80"
      - "443:443"
    restart: always
