version: '3.9'

networks:
  default:
    driver: bridge
  auth_service_default:
    external: true
  store_service_default:
    external: true

services:

  proxy:
    image: ${DOCKER_USER}/${APP_NAME}:${APP_VERSION}
    build: .
    env_file:
      - ../.env
      - .env
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/ssl/certs/nginx/
    ports:
      - "80:80"
      - "443:443"
    networks:
      - default
      - auth_service_default
      - store_service_default
    restart: always
