version: '3.9'


networks:
  default:
    driver: bridge
  auth_service_default:
    external: true

services:

  master:
    extends:
      file: ../auth_service_read/docker-compose.yml
      service: master
    volumes:
      - ./:/mnt/locust
  worker:
    extends:
      file: ../auth_service_read/docker-compose.yml
      service: worker
    volumes:
      - ./:/mnt/locust