version: '3.9'

networks:
  default:
    driver: bridge
  fastapi-ecommerce_default:
    external: true

services:

  master:
    extends:
      file: ../../.compose/docker-compose.yml
      service: master
    volumes:
      - ./:/mnt/locust
    networks:
      - default
      - fastapi-ecommerce_default

  worker:
    extends:
      file: ../../.compose/docker-compose.yml
      service: worker
    volumes:
      - ./:/mnt/locust
    networks:
      - default
      - fastapi-ecommerce_default