version: '3.9'

services:

  postgres:
    image: postgres:15
    env_file:
      - .env
    environment:
      - PGPORT=${PG_PORT}
      - PGTZ=${TZ}
    ports:
      - ${PG_PORT}:${PG_PORT}
    networks:
      - auth_service_net

  auth_service:
    build: .
    command: ./start.sh
    env_file:
      - .env
    environment:
      - APP_ENV=mongodb_cluster_prod
      - DEBUG=False
      - PG_HOST=postgres
      - RABBITMQ_HOST=queue
      - REDIS_HOST=redis
    depends_on:
      - postgres
    ports:
      - ${PORT}:${PORT}
    networks:
      - auth_service_net

networks:
  auth_service_net:
    name: custom_network
