version: '3'
services:

## Router
  store_service_router01:
    image: mongo:5.0
    container_name: store_service_router01
    command: mongos --port 27017 --configdb rs-config-server/store_service_configsvr01:27017 --bind_ip_all
    ports:
      - "27117:27017"
    volumes:
      - ./scripts:/scripts


## Config Servers
  store_service_configsvr01:
    image: mongo:5.0
    container_name: store_service_configsvr01 
    command: mongod --port 27017 --configsvr --replSet rs-config-server
    volumes:
      - ./scripts:/scripts 
    ports:
      - "27119:27017"
    links:
      - store_service_shard01_a
      - store_service_shard02_a
      - shard03-a
  

  ## Shards
  ##  01
   
  store_service_shard01_a:
    image: mongo:5.0
    container_name: store_service_shard01_a
    command: mongod --port 27017 --shardsvr --replSet rs-shard-01
    volumes:
      - ./scripts:/scripts
    ports:
      - "27122:27017"
    links:
      - store_service_shard01_b
      - store_service_shard01_c
  store_service_shard01_b:
    image: mongo:5.0
    container_name: shard-01-node-b
    command: mongod --port 27017 --shardsvr --replSet rs-shard-01
    volumes:
      - ./scripts:/scripts
    ports:
      - "27123:27017"
  store_service_shard01_c:
    image: mongo:5.0
    container_name: store_service_shard01_c
    command: mongod --port 27017 --shardsvr --replSet rs-shard-01
    volumes:
      - ./scripts:/scripts
    ports:
      - "27124:27017"

  ## Shards 02
  store_service_shard02_a:
    image: mongo:5.0
    container_name: store_service_shard02_a
    command: mongod --port 27017 --shardsvr --replSet rs-shard-02
    volumes:
      - ./scripts:/scripts
    ports:
      - "27125:27017"
    links:
      - store_service_shard02_b
      - store_service_shard02_c
  store_service_shard02_b:
    image: mongo:5.0
    container_name: store_service_shard02_b
    command: mongod --port 27017 --shardsvr --replSet rs-shard-02
    volumes:
      - ./scripts:/scripts
    ports:
      - "27126:27017"
  store_service_shard02_c:
    image: mongo:5.0
    container_name: store_service_shard02_c
    command: mongod --port 27017 --shardsvr --replSet rs-shard-02
    volumes:
      - ./scripts:/scripts
    ports:
      - "27127:27017"

  ## Shards 03
  shard03-a:
    image: mongo:5.0
    container_name: shard-03-node-a
    command: mongod --port 27017 --shardsvr --replSet rs-shard-03
    volumes:
      - ./scripts:/scripts
    ports:
      - "27128:27017"
    links:
      - shard03-b
      - shard03-c
  shard03-b:
    image: mongo:5.0
    container_name: shard-03-node-b
    command: mongod --port 27017 --shardsvr --replSet rs-shard-03
    volumes:
      - ./scripts:/scripts
    ports:
      - "27129:27017"
  shard03-c:
    image: mongo:5.0
    container_name: shard-03-node-c
    command: mongod --port 27017 --shardsvr --replSet rs-shard-03
    volumes:
      - ./scripts:/scripts
    ports:
      - "27130:27017"