apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-depl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: store
  template:
    metadata:
      labels:
        app: store
    spec:
      containers:
        - env:
            - name: STAGE
              valueFrom:
                configMapKeyRef:
                  key: STAGE
                  name: store-configmap
            - name: APP_MODULE
              valueFrom:
                configMapKeyRef:
                  key: APP_MODULE
                  name: store-configmap
            - name: AUTH_SERVICE_LOGIN_PATH
              valueFrom:
                configMapKeyRef:
                  key: AUTH_SERVICE_LOGIN_PATH
                  name: store-configmap
            - name: AUTH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  key: AUTH_SERVICE_URL
                  name: store-configmap
            - name: FIRST_SUPERUSER_EMAIL
              valueFrom:
                configMapKeyRef:
                  key: FIRST_SUPERUSER_EMAIL
                  name: store-configmap
            - name: FIRST_SUPERUSER_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: FIRST_SUPERUSER_PASSWORD
                  name: store-configmap
            - name: JWT_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  key: JWT_SECRET_KEY
                  name: store-configmap
            - name: MONGODB_URL
              valueFrom:
                configMapKeyRef:
                  key: MONGODB_URL
                  name: store-configmap
          image: coolworldocker/store_service:latest
          imagePullPolicy: Always
          name: store
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 512Mi
              cpu: 500m
            limits:
              memory: 1.5Gi
              cpu: 3000m
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: store-svc
spec:
  type: LoadBalancer
  selector:
    app: store
  ports:
    - port: 8082
      targetPort: 80
      protocol: TCP
