apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-nginx-configmap
  namespace: fastapi-ecommerce
data:
  default.conf: |
    upstream auth_svc {
        server auth-svc:8081;
    }    
    
    server {

        listen 80;

        location / {
            proxy_pass http://auth_svc;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host;
            proxy_redirect off;
        }
    }