apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:

  name: letsencrypt-prod
  namespace: fastapi-ecommerce
spec:
  acme:
    # Email address used for ACME registration
    email: fastapi.ecommerce@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Name of a secret used to store the ACME account private key
      name: letsencrypt-prod-fastapi-ecommerce-shop-key
    # Add a single challenge solver, HTTP01 using nginx
    solvers:
      - http01:
          ingress:
            class: nginx
