version: '3.9'

services:

  postgresql_master:
    extends:
      file: docker-compose.yml
      service: master
    volumes:
      - ./conf:/bitnami/postgresql/custom_conf

  postgresql_slave:
    extends:
      file: docker-compose.yml
      service: slave
    volumes:
      - ./conf:/bitnami/postgresql/custom_conf

  pgbouncer_master:
    extends:
      file: docker-compose.yml
      service: pgbouncer_master

  pgbouncer_slave:
    extends:
      file: docker-compose.yml
      service: pgbouncer_slave
