version: '3.9'

networks:
  default:
    driver: bridge
  auth_service_external_net:
    external: true

services:

  master:
    extends:
      file: docker-compose.yml
      service: master
    environment:
      - POSTGRESQL_PGHBA_REMOVE_FILTERS=scram-sha-256
    volumes:
      - ./pg_hba.test.conf:/bitnami/postgresql/conf

  slave:
    extends:
      file: docker-compose.yml
      service: slave

  pgbouncer_master:
    extends:
      file: docker-compose.yml
      service: pgbouncer_master

  pgbouncer_slave:
    extends:
      file: docker-compose.yml
      service: pgbouncer_slave
