version: '3.9'

networks:
  default:
    driver: bridge
  auth_service_external_net:
    external: true

services:

  master:
    extends:
      file: docker-compose.yml
      service: master
    ports:
      - "5432:5432"
    volumes:
      - ./conf/pg_hba.conf:/bitnami/postgresql/conf

  slave:
    extends:
      file: docker-compose.yml
      service: slave
    ports:
      - "5433:5432"

  pgbouncer_master:
    extends:
      file: docker-compose.yml
      service: pgbouncer_master
    ports:
      - "6433:6432"

  pgbouncer_slave:
    extends:
      file: docker-compose.yml
      service: pgbouncer_slave
    ports:
      - "6434:6432"
