version: '3.9'

networks:
  default:
    driver: bridge
  auth_service_default:
    external: true

services:

  master:
    extends:
      file: docker-compose.yml
      service: master
    environment:
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - POSTGRESQL_PGHBA_REMOVE_FILTERS=scram-sha-256
    volumes:
      - ./conf/test/pg_hba.conf:/bitnami/postgresql/conf

  slave:
    extends:
      file: docker-compose.yml
      service: slave
    environment:
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - POSTGRESQL_PGHBA_REMOVE_FILTERS=scram-sha-256

  pgbouncer_master:
    extends:
      file: docker-compose.yml
      service: pgbouncer_master
    environment:
      - PGUSER=postgres
      - PGPASSWORD=postgres

  pgbouncer_slave:
    extends:
      file: docker-compose.yml
      service: pgbouncer_slave
    environment:
      - PGUSER=postgres
      - PGPASSWORD=postgres
