version: '3.9'

services:

  postgresql_master:
    extends:
      file: docker-compose.yml
      service: master
    command: >
      ./conf/test/postgresql.conf >> /opt/bitnami/postgresql/conf/postgresql.conf

  postgresql_slave:
    extends:
      file: docker-compose.yml
      service: slave
    command: >
      ./conf/test/postgresql.conf >> /opt/bitnami/postgresql/conf/postgresql.conf

  pgbouncer_master:
    extends:
      file: docker-compose.yml
      service: pgbouncer_master

  pgbouncer_slave:
    extends:
      file: docker-compose.yml
      service: pgbouncer_slave
