version: '3.9'

networks:
  default:
    driver: bridge
  auth_service_external_net:
    external: true

services:

  master:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    env_file:
      - ../.env
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_SYNCHRONOUS_COMMIT_MODE=on
      - POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=${POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS:-1}
    networks:
      - default
      - auth_service_external_net
    volumes:
      - ./pg_hba.conf:/bitnami/postgresql/conf
      - ../.volumes/postgresql_master:/bitnami/postgresql
    restart: always


  slave:
    image: bitnami/postgresql:latest
    env_file:
      - ../.env
    ports:
      - "5432"
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_HOST=master
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
    networks:
      - default
      - auth_service_external_net
    restart: always


  pgbouncer_master:
    image: bitnami/pgbouncer:latest
    ports:
      - "6433:6433"
    env_file:
      - ../.env
    environment:
      - POSTGRESQL_HOST=master
      - POSTGRESQL_PORT=5432
      - PGBOUNCER_POOL_MODE=session
      - PGBOUNCER_PORT=6433
    networks:
      - default
      - auth_service_external_net
    restart: always


  pgbouncer_slave:
    image: bitnami/pgbouncer:latest
    ports:
      - "6434:6434"
    env_file:
      - ../.env
    environment:
      - POSTGRESQL_HOST=slave
      - POSTGRESQL_PORT=5432
      - PGBOUNCER_POOL_MODE=session
      - PGBOUNCER_PORT=6434
    networks:
      - default
      - auth_service_external_net
    restart: always
