version: '3.9'

networks:
  default:
    driver: bridge
  deploy_net:
    external: true

services:

  master:
    image: locustio/locust
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master --web-host 0.0.0.0 --web-port 8089
    ports:
      - "8089:8089"
    depends_on:
      - worker
    networks:
      - default
      - deploy_net

  worker:
    image: locustio/locust
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master
    networks:
      - default
      - deploy_net