apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  namespace: fastapi-ecommerce
spec:
  rules:
    - host: localhost
      http:
        paths:
          - pathType: Prefix
            path: "/api/v1/"
            backend:
              service:
                name: auth-svc
                port:
                  number: 8081
    - host: localhost
      http:
        paths:
          - pathType: Prefix
            path: "/api/v1/"
            backend:
              service:
                name: store-svc
                port:
                  number: 8082