apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-staging
  namespace: fastapi-ecommerce
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: fastapi.ecommerce@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx