version: '3.9'


services:

  auth_service_postgresql_master:
    image: bitnami/postgresql:latest
    container_name: auth_service_postgresql_master
    env_file:
      - ../../.env.auth_service
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_SYNCHRONOUS_COMMIT_MODE=on
      - POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=${POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS:-1}
    volumes:
      - ./conf:/bitnami/postgresql/custom_conf
      - ./scripts/:/docker-entrypoint-preinitdb.d
      - ../../.volumes/auth_service_postgresql/master/:/bitnami/postgresql
    restart: always


  auth_service_postgresql_slave:
    image: bitnami/postgresql:latest
    env_file:
      - ../../.env.auth_service
    ports:
      - "5432"
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_HOST=auth_service_postgresql_master
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
    volumes:
      - ./conf:/bitnami/postgresql/custom_conf
      - ./scripts/:/docker-entrypoint-preinitdb.d
    restart: always


  auth_service_pgbouncer_master:
    image: bitnami/pgbouncer:latest
    container_name: auth_service_pgbouncer_master
    ports:
      - "6433:6433"
    env_file:
      - ../../.env.auth_service
    environment:
      - POSTGRESQL_HOST=auth_service_postgresql_master
      - POSTGRESQL_PORT=5432
      - PGBOUNCER_POOL_MODE=session
      - PGBOUNCER_PORT=6433
    restart: always


  auth_service_pgbouncer_slave:
    image: bitnami/pgbouncer:latest
    container_name: auth_service_pgbouncer_slave
    ports:
      - "6434:6434"
    env_file:
      - ../../.env.auth_service
    environment:
      - POSTGRESQL_HOST=auth_service_postgresql_slave
      - POSTGRESQL_PORT=5432
      - PGBOUNCER_POOL_MODE=session
      - PGBOUNCER_PORT=6434
    restart: always
