version: '3.9'

services:

  auth_service_postgresql_master:
    image: bitnami/postgresql:latest
    container_name: auth_service_postgresql_master
    env_file:
      - ../.env
      - ../.env.prod
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_SYNCHRONOUS_COMMIT_MODE=on
      - POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=${POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS:-1}
      - POSTGRESQL_TCP_KEEPALIVES_INTERVAL=0
      - POSTGRESQL_TCP_KEEPALIVES_IDLE=0
      - POSTGRESQL_TCP_KEEPALIVES_COUNT=10
    volumes:
      - ./conf:/bitnami/postgresql/custom_conf
      - ./scripts/:/docker-entrypoint-preinitdb.d
      - auth_service_postgresql_master:/bitnami/postgresql
    restart: always

  auth_service_pgbouncer_master:
    image: bitnami/pgbouncer:latest
    container_name: auth_service_pgbouncer_master
    ports:
      - "6432:6432"
    env_file:
      - ../.env
      - ../.env.prod
    environment:
      - POSTGRESQL_HOST=auth_service_postgresql_master
      - POSTGRESQL_PORT=5432
      - PGBOUNCER_POOL_MODE=session
      - PGBOUNCER_PORT=6432
    restart: always

  auth_service_postgresql_replica_01:
    image: bitnami/postgresql:latest
    container_name: auth_service_postgresql_replica_01
    env_file:
      - ../.env
      - ../.env.prod
    ports:
      - "5433:5432"
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_HOST=auth_service_postgresql_master
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_TCP_KEEPALIVES_INTERVAL=0
      - POSTGRESQL_TCP_KEEPALIVES_IDLE=0
      - POSTGRESQL_TCP_KEEPALIVES_COUNT=10
    volumes:
      - ./conf:/bitnami/postgresql/custom_conf
      - ./scripts/:/docker-entrypoint-preinitdb.d
      - auth_service_postgresql_replica_01:/bitnami/postgresql
    restart: always
  auth_service_pgbouncer_replica_01:
    image: bitnami/pgbouncer:latest
    container_name: auth_service_pgbouncer_replica_01
    ports:
      - "6433:6432"
    env_file:
      - ../.env
      - ../.env.prod
    environment:
      - POSTGRESQL_HOST=auth_service_postgresql_replica_01
      - POSTGRESQL_PORT=5432
      - PGBOUNCER_POOL_MODE=session
      - PGBOUNCER_PORT=6432
    volumes:
      - auth_service_pgbouncer_replica_01:/bitnami/pgbouncer/conf/
    restart: always

  auth_service_postgresql_replica_02:
    image: bitnami/postgresql:latest
    container_name: auth_service_postgresql_replica_02
    env_file:
      - ../.env
      - ../.env.prod
    ports:
      - "5434:5432"
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_HOST=auth_service_postgresql_master
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_TCP_KEEPALIVES_INTERVAL=0
      - POSTGRESQL_TCP_KEEPALIVES_IDLE=0
      - POSTGRESQL_TCP_KEEPALIVES_COUNT=10
    volumes:
      - ./conf:/bitnami/postgresql/custom_conf
      - ./scripts/:/docker-entrypoint-preinitdb.d
      - auth_service_postgresql_replica_02:/bitnami/postgresql
    restart: always
  auth_service_pgbouncer_replica_02:
    image: bitnami/pgbouncer:latest
    container_name: auth_service_pgbouncer_replica_02
    ports:
      - "6434:6432"
    env_file:
      - ../.env
      - ../.env.prod
    environment:
      - POSTGRESQL_HOST=auth_service_postgresql_replica_02
      - POSTGRESQL_PORT=5432
      - PGBOUNCER_POOL_MODE=session
      - PGBOUNCER_PORT=6432
    volumes:
      - auth_service_pgbouncer_replica_02:/bitnami/pgbouncer/conf/
    restart: always

volumes:
  auth_service_postgresql_master:
    labels:
      keep:
  auth_service_pgbouncer_master:
    labels:
      keep:

  auth_service_postgresql_replica_01:
    labels:
      keep:
  auth_service_pgbouncer_replica_01:
    labels:
      keep:

  auth_service_postgresql_replica_02:
    labels:
      keep:
  auth_service_pgbouncer_replica_02:
    labels:
      keep: