version: '3.9'

services:

  auth_service_postgresql_master:
    image: bitnami/postgresql:latest
    user: root
    container_name: auth_service_postgresql_master
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=1
      - POSTGRESQL_SYNCHRONOUS_COMMIT_MODE=on
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
    env_file:
      - .env
    volumes:
      - ./postgresql/conf:/bitnami/postgresql/conf
      - ./scripts:/docker-entrypoint-preinitdb.d
      - ./.volumes/postgresql_master:/bitnami/postgresql
    restart: always

  auth_service_pgbouncer_master:
    image: bitnami/pgbouncer:latest
    container_name: auth_service_pgbouncer_master
    ports:
      - "6432:6432"
    environment:
      - POSTGRESQL_HOST=auth_service_postgresql_master
      - PGBOUNCER_POOL_MODE=session
    env_file:
      - .env
    restart: always

  auth_service_postgresql_replica_01:
    image: bitnami/postgresql:latest
    user: root
    container_name: auth_service_postgresql_replica_01
    ports:
      - "5434:5432"
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_HOST=auth_service_postgresql_master
    volumes:
      - ./postgresql/conf:/bitnami/postgresql/conf
      - ./scripts:/docker-entrypoint-preinitdb.d
      - ./.volumes/postgresql_replica_01:/bitnami/postgresql
    env_file:
      - .env
    restart: always

  auth_service_pgbouncer_replica_01:
    image: bitnami/pgbouncer:latest
    container_name: auth_service_pgbouncer_replica_01
    ports:
      - "6434:6432"
    environment:
      - POSTGRESQL_HOST=auth_service_postgresql_replica_01
      - PGBOUNCER_POOL_MODE=session
    env_file:
      - .env
    restart: always

  auth_service_postgresql_replica_02:
    image: bitnami/postgresql:latest
    user: root
    container_name: auth_service_postgresql_replica_02
    ports:
      - "5435:5432"
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_HOST=auth_service_postgresql_master
    env_file:
      - .env
    volumes:
      - ./postgresql/conf:/bitnami/postgresql/conf
      - ./scripts:/docker-entrypoint-preinitdb.d
      - ./.volumes/postgresql_replica_02:/bitnami/postgresql
    restart: always

  auth_service_pgbouncer_replica_02:
    image: bitnami/pgbouncer:latest
    container_name: auth_service_pgbouncer_replica_02
    ports:
      - "6435:6432"
    environment:
      - POSTGRESQL_HOST=auth_service_postgresql_replica_02
      - PGBOUNCER_POOL_MODE=session
    env_file:
      - .env
    restart: always
