version: '3.9'

networks:
  bridge_net:
    driver: bridge

services:

  # AUTH_SERVICE
  auth_service:
    image: coolworldocker/auth_service:latest
    extends:
      service: auth_service
      file: ../src/auth_service/docker-compose.yml
    env_file:
      - ../.env
    networks:
      - bridge_net


  ## POSTGRESQL
  auth_service_postgresql_master:
    extends:
      service: auth_service_postgresql_master
      file: ../src/auth_service/postgresql/docker-compose.yml
    networks:
      - bridge_net

  auth_service_pgbouncer_master:
    extends:
      service: auth_service_pgbouncer_master
      file: ../src/auth_service/postgresql/docker-compose.yml
    networks:
      - bridge_net

  auth_service_postgresql_replica_01:
    extends:
      service: auth_service_postgresql_replica_01
      file: ../src/auth_service/postgresql/docker-compose.yml
    networks:
      - bridge_net
  auth_service_pgbouncer_replica_01:
    extends:
      service: auth_service_pgbouncer_replica_01
      file: ../src/auth_service/postgresql/docker-compose.yml
    networks:
      - bridge_net

  auth_service_postgresql_replica_02:
    extends:
      service: auth_service_postgresql_replica_02
      file: ../src/auth_service/postgresql/docker-compose.yml
    networks:
      - bridge_net
  auth_service_pgbouncer_replica_02:
    extends:
      service: auth_service_pgbouncer_replica_02
      file: ../src/auth_service/postgresql/docker-compose.yml
    networks:
      - bridge_net

  #---------------------------------------------------------------------------------------------------------------------

  # STORE_SERVICE
  store_service:
    image: coolworldocker/store_service:latest
    extends:
      service: store_service
      file: ../src/store_service/docker-compose.yml
    env_file:
      - ../.env
    networks:
      - bridge_net

  ## MONGODB
  store_service_router01:
    extends:
      service: store_service_router01
      file: ../src/store_service/mongodb/docker-compose.yml
    networks:
      - bridge_net

  store_service_configsvr01:
    extends:
      service: store_service_configsvr01
      file: ../src/store_service/mongodb/docker-compose.yml
    networks:
      - bridge_net

  store_service_shard01_a:
    extends:
      service: store_service_shard01_a
      file: ../src/store_service/mongodb/docker-compose.yml
    networks:
      - bridge_net
  store_service_shard01_b:
    extends:
      service: store_service_shard01_b
      file: ../src/store_service/mongodb/docker-compose.yml
    networks:
      - bridge_net
  store_service_shard01_c:
    extends:
      service: store_service_shard01_c
      file: ../src/store_service/mongodb/docker-compose.yml
    networks:
      - bridge_net

  store_service_shard02_a:
    extends:
      service: store_service_shard02_a
      file: ../src/store_service/mongodb/docker-compose.yml
    networks:
      - bridge_net
  store_service_shard02_b:
    extends:
      service: store_service_shard02_b
      file: ../src/store_service/mongodb/docker-compose.yml
    networks:
      - bridge_net
  store_service_shard02_c:
    extends:
      service: store_service_shard02_c
      file: ../src/store_service/mongodb/docker-compose.yml
    networks:
      - bridge_net
  
  store_service_shard03_a:
    extends:
      service: store_service_shard03_a
      file: ../src/store_service/mongodb/docker-compose.yml
    networks:
      - bridge_net
  store_service_shard03_b:
    extends:
      service: store_service_shard03_b
      file: ../src/store_service/mongodb/docker-compose.yml
    networks:
      - bridge_net
  store_service_shard03_c:
    extends:
      service: store_service_shard03_c
      file: ../src/store_service/mongodb/docker-compose.yml
    networks:
      - bridge_net

  #---------------------------------------------------------------------------------------------------------------------

  # PROXY_SERVICE
  proxy_service:
    image: coolworldocker/proxy_service:latest
    extends:
      service: proxy_service
      file: ../src/proxy_service/docker-compose.yml
    networks:
      - bridge_net

  #---------------------------------------------------------------------------------------------------------------------

  # MONITORING

  monitoring_portainer:
    extends:
      service: monitoring_portainer
      file: ../src/monitoring/docker-compose.yml
    networks:
      - bridge_net

volumes:
  auth_service_postgresql_master:
    labels:
      keep:
  auth_service_pgbouncer_master:
    labels:
      keep:

  auth_service_postgresql_replica_01:
    labels:
      keep:
  auth_service_pgbouncer_replica_01:
    labels:
      keep:

  auth_service_postgresql_replica_02:
    labels:
      keep:
  auth_service_pgbouncer_replica_02:
    labels:
      keep:

  store_service_mongodb_router01_db:
    labels:
      keep:
  store_service_mongodb_router01_config:
    labels:
      keep:

  store_service_mongodb_configsvr01_db:
    labels:
      keep:
  store_service_mongodb_configsvr01_config:
    labels:
      keep:

  store_service_mongodb_shard01_a_db:
    labels:
      keep:
  store_service_mongodb_shard01_a_config:
    labels:
      keep:
  store_service_mongodb_shard01_b_db:
    labels:
      keep:
  store_service_mongodb_shard01_b_config:
    labels:
      keep:
  store_service_mongodb_shard01_c_db:
    labels:
      keep:
  store_service_mongodb_shard01_c_config:
    labels:
      keep:

  store_service_mongodb_shard02_a_db:
    labels:
      keep:
  store_service_mongodb_shard02_a_config:
    labels:
      keep:
  store_service_mongodb_shard02_b_db:
    labels:
      keep:
  store_service_mongodb_shard02_b_config:
    labels:
      keep:
  store_service_mongodb_shard02_c_db:
    labels:
      keep:
  store_service_mongodb_shard02_c_config:
    labels:
      keep:
  
  
  store_service_mongodb_shard03_a_db:
    labels:
      keep:
  store_service_mongodb_shard03_a_config:
    labels:
      keep:
  store_service_mongodb_shard03_b_db:
    labels:
      keep:
  store_service_mongodb_shard03_b_config:
    labels:
      keep:
  store_service_mongodb_shard03_c_db:
    labels:
      keep:
  store_service_mongodb_shard03_c_config:
    labels:
      keep: