version: '3.9'

services:
  store_service:
    build: .
    container_name: store_service
    env_file:
      - .env
      - .env.prod
    ports:
      - "80"
    volumes:
      - ../.volumes/store_service/log/:/app/store_service/.logs/
      - ../.volumes/store_service/htmlcov/:/app/htmlcov/
    restart: always


