version: '3.9'

services:
  store_service:
    build: .
    env_file:
      - .env
    environment:
      - MONGODB_URL=mongodb://store_service_mongodb_router01:27017/app
    ports:
      - "80"
    restart: always


