version: '3.9'

services:

  store_service:
    build: .
    env_file:
      - .env
      - ../../.env
    ports:
      - "80"
    restart: always
    deploy:
      replicas: 2
      placement:
        constraints: [ node.role == worker ]
      update_config:
        failure_action: rollback


