version: '3.9'

networks:
  default:
    driver: bridge
  external_net:
    driver: bridge
  auth_service_external_net:
    external: true


services:

  store_service:
    image: ${DOCKER_USER}/${APP_NAME}:${APP_VERSION}
    build: .
    env_file:
      - .env
      - ../.env
    ports:
      - ${APP_PORT}:80
    networks:
      - default
      - external_net
      - auth_service_external_net
