version: '3.9'

networks:
  app_tier:
    name: mss_network

services:

  store_service:
    build: .
    command: ./start.sh
    env_file:
      - .env
    environment:
      - DATABASE_URL=mongodb://host.docker.internal:27117,host.docker.internal:27118/app
    ports:
      - ${PORT}:${PORT}
    networks:
      - app_tier

