version: '3.9'

services:

  store_service:
    build: .
    command: ./start.sh
    env_file:
      - .env
    environment:
      - DEBUG=False
      - DATABASE_URL=mongodb://localhost:27117,localhost:27118/app
    ports:
      - ${PORT}:${PORT}

