version: '3.9'

networks:
  app_tier:
    name: mss_network
    external: true

services:

  store_service:
    build: .
    command: ./start.sh
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    networks:
      - app_tier

