version: '3.9'
services:
  
  mongo:
    image: candis/mongo-replica-set
    ports:
      - "27017:27017"
      - "27018:27018"
      - "27019:27019"

  store_service:
    build: .
    command: ./start.sh
    env_file:
      - .env
    environment:
      - MONGODB_URL=mongodb://mongo:27017,mongo:27018,mongo:27019/app?replicaSet=rs0&readPreference=primary&ssl=false
    ports:
      - ${PORT}:${PORT}
