version: '3.9'

services:

  store_service:
    build: .
    command: ./start.sh
    env_file:
      - .env
    environment:
      - DEBUG=False
      - AUTH_SERVICE_API=http://host.docker.internal:8001
    ports:
      - ${PORT}:${PORT}

