#file: noinspection YAMLSchemaValidation
name: Deploy

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build images and publish to registry
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
          export APP_ENV=test
          export DEBUG=True
          bash cpenv.sh
          bash build_push.sh
          bash build_up.sh
          bash test.sh

  build:
    name: Build
    needs: [ test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deployment on VDS - copy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "."
          target: "/root/fastapi_ecommerce/"


      - name: Deployment on VDS - start
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /root/fastapi_ecommerce/
            echo "${{ secrets.ENV_FILE }}" > .env
            chmod +x cpenv.sh
            bash cpenv.sh
            chmod +x build_up.sh
            bash build_up.sh
            chmod +x test.sh
            bash test.sh
