#file: noinspection YAMLSchemaValidation
name: Deploy
on:
  push:
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deployment on VDS - copy code
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "."
          target: "/root/fastapi_ecommerce/"

      - name: Deployment on VDS - restart services
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /root/fastapi_ecommerce/
            echo "${{ secrets.ENV_FILE }}" > src/.env
            cd src/scripts
            chmod +x cpenv.sh
            bash cpenv.sh
            chmod +x restart.sh
            bash restart.sh
            bash test.sh