#file: noinspection YAMLSchemaValidation
name: Deploy

on:
  push:
    branches:
      - master

env:
  AUTH_SERVICE_IMAGE: coolworldocker/auth_service
  STORE_SERVICE_IMAGE: coolworldocker/store_service
  PROXY_IMAGE: coolworldocker/proxy
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    name: Build services

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create .env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
      - name: Install mkcert
        run: sudo apt install -y libnss3-tools mkcert

      - name: Create ssl cert
        run: |
          bash -x ./cpenv.sh
          cd ./proxy
          bash -x ./mkcert.sh
          cd ..
        

      - name: Build image and publish to registry
        run: |
          docker build -t $AUTH_SERVICE_IMAGE:latest ./auth_service
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
          docker push $AUTH_SERVICE_IMAGE:latest
          
          docker build -t $STORE_SERVICE_IMAGE:latest ./store_service
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
          docker push $STORE_SERVICE_IMAGE:latest
            
          docker build -t $PROXY_IMAGE:latest ./proxy
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
          docker push $PROXY_IMAGE:latest

      - name: Copy repository contents via scp
        uses: appleboy/scp-action@master
        env:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.OPENSSH_PRIVATE_KEY }}
        with:
          source: "."
          target: "/root"

      - name: Create .env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
      - name: Install mkcert
        run: sudo apt install -y libnss3-tools mkcert

      - name: Create ssl cert
        run: |
          bash -x ./cpenv.sh
          cd ./proxy
          bash -x ./mkcert.sh
          cd ..

      - name: Executing remote command - Deployment on VDS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.OPENSSH_PRIVATE_KEY }}
          script: |
            cd /root/fastapi-ecommerce
            echo "${{ secrets.ENV_FILE }}" > .env
            bash -x ./cpenv.sh
            bash -x ./build.prod.sh