#file: noinspection YAMLSchemaValidation
name: Deploy
on:
  push:
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build images and publish to registry
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
          ls
          bash src/scripts/cpenv.sh
          export APP_ENV=test
          bash src/scripts/restart.sh

  build:
    name: Build
    needs: [ test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deployment on VDS - copy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "."
          target: "/root/fastapi_ecommerce/"

      - name: Deployment on VDS - start
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /root/fastapi_ecommerce/
            echo "${{ secrets.ENV_FILE }}" > .env
            chmod +x src/scripts/cpenv.sh
            bash src/scripts/cpenv.sh
            chmod +x src/scripts/restart.sh
            bash src/scripts/restart.sh