#file: noinspection YAMLSchemaValidation
name: Deploy

on:
  push:
    branches:
      - master

env:
  AUTH_SERVICE_IMAGE: coolworldocker/auth_service
  STORE_SERVICE_IMAGE: coolworldocker/store_service
  PROXY_IMAGE: coolworldocker/proxy
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    name: Build Container

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build image and publish to registry
        run: |
          docker build -t AUTH_SERVICE_IMAGE:latest ./auth_service
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
          docker push $IMAGE_NAME:latest
          
          docker build -t STORE_SERVICE_IMAGE:latest ./store_service
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
          docker push $IMAGE_NAME:latest
            
          docker build -t PROXY_IMAGE:latest ./proxy
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
          docker push $IMAGE_NAME:latest
