name: deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_APP_ENV: prod
          envkey_DEBUG: false

          directory: /
          file_name: .env.example
          fail_on_empty: true

      - name: Build services
        run: |
          chmod +x ./build.prod.sh
          bash -x ./build.prod.sh
