name: Test
on:
  push:
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build images and publish to registry
        run: |
          echo "${{ secrets.ENV_FILE }}" > src/.env
          ls
          cd src/scripts
          bash cpenv.sh
          export APP_ENV=test
          bash restart.sh
          bash test.sh